require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false
production = ENV["PRODUCTION"] == "1"

target 'MonthlyCostTracker' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'MonthlyCostTrackerTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'MonthlyCostTracker-tvOS' do
  # Pods for MonthlyCostTracker-tvOS

  target 'MonthlyCostTracker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
