# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false
production = ENV["PRODUCTION"] == "1"

target 'MonthlyCostTracker' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'MonthlyCostTrackerTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'MonthlyCostTracker-tvOS' do
  # Pods for MonthlyCostTracker-tvOS

  target 'MonthlyCostTracker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
